### ISSUE TITLE
Decide if it's a good idea to keep using Material UI

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#121]
Material UI has multiple limitation that might lead us to future problems, investigate if it's worth changing everything so far to CSS or to stick to Material UI

**Comment by marcovidonis** [comment]
Personally, I find MUI useful to get started quickly and to get something that looks ok out of the box, since I'm no designer 😅. But I don't necessarily see it as the final design.

I'm ok with replacing it with a custom design, but this means having someone create a bespoke design system for the project. After we have that, we'll need to replace all of MUI's components with our own custom ones, so this is potentially a big job.
I'd love to see it done, but I would argue is not a top priority until we have the platform capable of running hybrid events properly, not just video calls.

What do you think?

**Comment by fpyoung** [comment]
@JonaQuaLabs has been thinking about this and came to the conclution that is worth keeping MUI for multiple reasons: 
- Is not a scaling application.
- The component quantity won't grow overtime.
- If we want some CSS we can use style components.

**Comment by marcovidonis** [comment]
Ok. Should we close the issue then?
