### ISSUE TITLE
When creating a room create a new table for the chat

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#244]

**Comment by juanpqualabs** [comment]
I was researching this ticket, and from what I found creating a new table for each chat is not the best solution.
The best is to use the existing 'message-chat' table and add a new column 'chat_id' to this table in order to identify to which chat this message was sent.
[This thread](https://github.com/orgs/supabase/discussions/3852) asks to implement something similar to what we want to do and that is the basis of my answer .
If you agree with this let's close this ticket and create others to implement the chat in this new way.

**Comment by fpyoung** [comment]
hey Pique great job! you avoided the team on doing something that was a bad practice.
Yes for what I read on the link you posted this is the way to proceed! 
I'll get rid of the other issues that were related to this change.
